### ISSUE TITLE
[TODO] Saturday pre-testing trip

### ISSUE THREAD

**Issue by nistath** [MITMotorsports/MY18#21]
Things to do before testing tomorrow in descending importance (do topmost first):

- [x] [VCU] Transmit over CAN the controls configuration used by the VCU.

  This is both for logging purposes and for the next item.

  Title it `VCUControlsParams`.

- [x] [Dash] Set each value in `DashRequest` to the corresponding value in `VCUControlsParams` upon entry in a page with unknown values.

  This means that at steady state (CAN messages came in), a question mark should never show up in place of a value.

  This would also work in the case of the critical page -- the limp factor and default regen value should be coming from the VCU.

- [x] [Dash] Add ESTOP hit indication in critical page.

  There should be a prinout in the critical page that reads "ESTOP" if `carstats.vcu_state.estop_hit` and "" otherwise.

- [ ] [Dash] Add TSMS open indication in critical page.

  FATAL:CONTACTOR faults are monostable. If the TSMS is open, when the car moves from `VCU_LV` to `VCU_PRECHARGE` it will fault and go down to `VCU_LV` or `VCU_ROOT` (no guarantee as to which since I will change it soon, so do not rely on this).

  The fault will only appear very momentarily. On the dash you need to catch this fault and latch on some state variable that indicates TSMS was left open and thus precharge failed. This variable must remain latched on until the car enters `VCU_RTD` when it latches off.

  There should be a printout in the critical page that reads "TSMS" if the variable is latched on and "" otherwise. Ideally this would be next/on top of the ESTOP printout.

- [ ] [Dash] Debug button_listener actions.

  Today the dash rapidly cycled through many pages whenever tapped. I changed it back to A.rising_edge but we should fix that. I think that actions should only happen momentarily -- TAP pulses if button is released before the threshold and HOLD pulses at the threshold.

**Comment by daniwhite** [comment]
There is not enough space for everything on the dash critical page, so to consolidate my scheme is to combine regen, temp limiting, and voltage limiting on one half-line, and put TSMS + E stop on the same line as the F/R indicator
